[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["BendCoinPool", "BendNftPool", "BendStakeManager", "NftVault", "StBAYC", "LendingMigrator"]

[fmt]
line_length = 120

[fuzz]
runs = 32